Repository morty-faas/morty, pull requests merged in 2023-04, with the labels that each got.

#2 docs: add AUTHORS.md
  AUTHORS.md
Labels: documentation, skip-changelog

#6 build: security policies
  SECURITY.md
Labels: chore, skip-changelog

#8 Fix Go issues after first golangci lint
  controller/api/server.go
  controller/orchestration/rik/mapper.go
  controller/state/memory/memory.go
  controller/state/redis/redis.go
  pkg/archive/archive.go
  pkg/helpers/lz4.go
  registry/builder/builder.go
  registry/registry/health.go
  registry/registry/server.go
Labels: fix, patch
